---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  pdf_document: default
---
```{r}
library(tidyverse)
library(psych)
```


```{r}
churn_df <- read.csv("/Users/wyattromero/Downloads/Principal-Component-Analysis/churn_clean.csv")
head(churn_df)
```

```{r}
str(churn_df)
```

```{r}
churn_df <- select(churn_df, c('Age', 'Income', 'Outage_sec_perweek', 'MonthlyCharge', 'Bandwidth_GB_Year', 'Tenure', 'Churn'))
head(churn_df)
```

```{r}
churn_df_scaled <- scale(churn_df[1:6])
head(churn_df_scaled)
```

```{r}
write.csv(churn_df_scaled, "Churn_prepared_D212_2.csv", row.names =TRUE)
```


```{r}
set.seed(111)
ind <- sample(2, nrow(churn_df_scaled),
              replace = TRUE,
              prob = c(0.8, 0.2))
training <- churn_df_scaled[ind==1,]
testing <- churn_df_scaled[ind==2,]
```

```{r}
pairs.panels(training[,-7],
             gap = 0,
             bg = c("red", "yellow", "blue") [churn_df$Churn],
             pch=21)
```

```{r}
pc <- prcomp(training[,-7],
            center = TRUE,
            scale. = TRUE)
attributes(pc)
```

```{r}
pc$center
```

```{r}
pc$scale
```

```{r}
print(pc)
```

```{r}
summary(pc)
```

```{r}
variance = pc$sdev^2 / sum(pc$sdev^2)
variance
```

```{r}
qplot(c(1:6), variance) +
  geom_line() +
  geom_point(size=4) +
  xlab("Principal Component") +
  ylab("Variance Explained") +
  ggtitle("Scree Plot")
  ylim(0, 1)
```

